apiVersion: v1
kind: Namespace
metadata:
  name: aula-platform-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: aula-platform-namespace
  name: chatbot
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: chatbot
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chatbot
    spec:
      containers:
        - image: 374521230244.dkr.ecr.ap-south-1.amazonaws.com/chatbot:dev-64acfa0207a8795f7e619e62d5746ad2e44545a3
          imagePullPolicy: IfNotPresent
          name: chatbot
          ports:
            - containerPort: 8096
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-host
          resources:
            limits:
              cpu: "0.50"
              memory: "513Mi"
            requests:
              cpu: "0.25"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  namespace: aula-platform-namespace
  name: chatbot
spec:
  ports:
    - port: 8096
      targetPort: 8096
      protocol: TCP
  selector:
    app.kubernetes.io/name: chatbot
